<?php 
/*------------------------------------------------
# Author: Kirsten K. Meymaris (UCAR)
# Modified by Rich Zigrino
# Modified by Greg Newman (NewmanDesigns.org) 
# Last modified 1/9/11
# Copyright 2008-2011 All Rights Reserved	
# National Ecological Observation Network (NEON), 	
# Chicago Botanic Garden, & University of Montana	
--------------------------------------------------*/

require 'cgi-bin/db_connect.php';
require_once 'cgi-bin/pb_lib.php';

if(isset ($_GET['Station_ID']))
{
	$stationid = $_GET["Station_ID"];
}
else
{
	$stationid = $_POST["stationid"];
}

if(isset ($_GET['plantgroupid']))
{
	$plantgroupid = $_GET["plantgroupid"];
}
else
{
	$plantgroupid = $_POST["plantgroupid"];
}

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<?php
HeaderStart("Project BudBurst - Register a Plant"); // The first and only parameter is the page title
//
// place script tags and or style tags here if needed
?>

<script src="jquery-ui-1.9.0.custom/js/jquery-1.8.2.js" type="text/javascript"></script>
<script language="javascript" src="js/menuswap.js"></script>
	
<!--JavaScript function located this far down to accomodate creation of PHP vars for stationid, personid, speciesid-->
<script type="text/javascript">
function form1Submit()
{
	document.getElementById("form1").submit();

}

function form2Submit()
{
	document.getElementById("form2").submit();

}
</script>

<?php
//
HeaderEnd();
?>

<body id="MyBudBurst">

<div id="wrapper">

 <div id="contentwrapper">
  	
    <!--<div><a href="index.php"><img src="images/Banner_1.jpg" width="762" height="165" alt="Project BudBurst" title="Project BudBurst" border="0" /></a></div>-->
    
	<?php
		WriteTopLogin($dbh);
	?>
    
    <!-- Top Navigation -->

	<?php	
		WriteTopNavigation();
	?>

<div id="MainContent">
    <h1>Enter Regular Reports - Register a Plant</h1>
      
    <?php
		$maincontent='';
		$flag=0; 

		 //make sure user is logged in
		if(!checklogin($dbh))
		{
				$maincontent.='<p>Sorry you are not logged in. This area is restricted to registered members.</p>';
				$maincontent.='<p>Continue by <a class="maincontent" href="login.php">logging in</a>.';
				$maincontent.= $spacer;
				$flag=1;
		}
		else
		{
			if (isset($_POST['btnsubmit']))
			{
				//if a required field is empty, error message
				//if (!($_POST['stationid'] && ($_POST['speciesid'] || $_POST['common_name_userdef'])))
				// check to see if station id and species id are set.  Also check to see if species id is set to 999-Other and if so,
				// is did the visitor provide the common name?
				if (!(($_POST['stationid']) && ($_POST['speciesid'])) || ($_POST['speciesid']=='999' && !$_POST['common_name_userdef']))
				{
					$maincontent.='<p> Plant Registration - You did not fill in a required field.</p> 
					<p>Please go back and try again.</p>
					<FORM><INPUT TYPE="button" VALUE="Back" onClick="history.go(-1);return true;"> </FORM>';
					$flag=1;	
				}
					
					//everything should be good at this point

					//Set Species ID
					//if other species, save in Species table and get autogenerated species id
					//todo if other common name reported this is higher priority than from selected list??
					if($_POST['common_name_userdef'])
					{
						$common_name_userdef = $_POST['common_name_userdef'];
					
						if(!$_POST['genus_userdef']){$genus_udef='';}
						else $genus_udef=$_POST['genus_userdef'];
					
						if(!$_POST['species_userdef']){$species_udef='';}
						else $species_udef=$_POST['species_userdef'];
						
						$qry = sprintf("INSERT INTO tbl_species (
						Common_Name, 
						Genus, 
						Species,
						User_Defined) 
						values ('%s','%s','%s',1)", //1=user_defined
						$dbh->real_escape_string($_POST['common_name_userdef']),
						$dbh->real_escape_string($genus_udef),
						$dbh->real_escape_string($species_udef)
						);
						
						$check = $dbh->query($qry);
						if ($dbh->affected_rows == 0)
						{
							$maincontent.='<p>Error - Could not add to database:Species</p> 
								<p>Please go back and try again.</p>
								<FORM>
								<INPUT TYPE="button" VALUE="Back" onClick="history.go(-1);return true;"> 
								</FORM>';
							$flag=1;	
						} 
						else 
						{
							$speciesid_verified = $dbh->insert_id;
							//echo '<br> species verified = '.$speciesid_verified;
							
							//store in rel_species_protocol based on plant group selection
							//TODO have user select protocol group instead of plant group to decide pollination?
							if (!isset($_POST['plantgroupid']) ||  ($_POST['plantgroupid']==0))
							{
								$protocolid = get_other_protocol_id($dbh);
							}
							else
							{
								$protocolid = get_protocol_id($dbh, $_POST['plantgroupid']);
							}
							//echo 'Protocolid = ' . $protocolid . '<br>';
							$qry = sprintf("INSERT INTO rel_species_protocol (Species_ID,Protocol_ID) values (%d, %d)", 																		
								$dbh->real_escape_string($speciesid_verified),$dbh->real_escape_string($protocolid)
							);
							
							$check = $dbh->query($qry);
							//echo $qry;
							//echo "Error message = " . mysqli_error($dbh) . "<br>";
							if ($dbh->affected_rows == 0)
							{
								$maincontent.='<p>Error - Could not add to database:rel_species_protocol</p> 
									<p>Please go back and try again.</p>
									<FORM>
									<INPUT TYPE="button" VALUE="Back" onClick="history.go(-1);return true;"> 
									</FORM>';
								$flag=1;		
							} //if
							else
							{ 
									//everything a-okay
									//echo 'Protocolid = ' . $protocolid . '<br>';
									//echo "species protocol has been added";
							}
						}//else
					}//end if common_name_userdef
					else
					//PBB species
					{
						//use selected species id
						$speciesid_verified = $_POST['speciesid'];
					}



					
				//check to see if species already registered at this site
				//fetch speciesid registered at this site
				$myregisteredspecies = get_myBudBurst_plants($stationid, $dbh);
									  
				while ($myregisteredspeciesrow = $myregisteredspecies->fetch_object())
				{
					//get species ids
					$registeredspeciesid=$myregisteredspeciesrow->Species_ID;
				
					//if match between species visitor is trying to add and one of the registered species
					//trip error flag and set $maincontent output to display conflict message
					if($registeredspeciesid == $speciesid_verified)
					{
						//fetch common name for results 'echo' below
						$result_plantNames = get_plant($dbh,$speciesid_verified);
	
						while($row_plantName = $result_plantNames->fetch_object())
						{
							$commonName = $row_plantName->Common_Name;
						}//while
						
						//fetch site location name
						$siteName = get_StationName($dbh,$stationid);
					
						$flag=1; // set error flag so insert record section below won't be called
						$maincontent.='You already have ' . $commonName . ' registered at ' . $siteName . '. ';
						$maincontent.='To report on a second instance of ' . $commonName . ' at the same location, please ';
						$maincontent.='<a href="my_regular_reports.php">register</a> a new site and add the plant to that site.';
					} // end if registered plant matches plant being added
				}//end while loop through registered plants for this site
				
				//if okay store in rel_station_species table
				if(!$flag)
				{
					//check to see if plant was formerly deleted (where active=0 in rel_station_species table)
					$qry = sprintf("SELECT Station_Id, Species_Id FROM rel_station_species WHERE Station_Id = '%d' AND Species_Id ='%d' AND active = '0'", $dbh->real_escape_string($_POST['stationid']),$dbh->real_escape_string($_POST['speciesid']));
					
					$result = $dbh->query($qry);

					//redirect to my_regular_reports.php on success
					//$maincontent.= "<script> window.location.replace('my_regular_reports.php') </script>";

					$num_rows = $result->num_rows;
					
					if ($num_rows != 0)
					{ //found previous record, set active=1 for record in rel_station_species table
						$qry = sprintf("UPDATE rel_station_species SET active=1 WHERE Station_Id='%d' AND Species_Id='%d' ", 
						$_POST['stationid'], $_POST['speciesid']);
						$result = $dbh->query($qry);
					}
					else
					{ //no previous record found, insert new record into rel_station_species table
						$qry = sprintf("INSERT INTO rel_station_species (Station_ID, Species_ID) values ('%d', '%d')", 
						$dbh->real_escape_string($_POST['stationid']),
						$dbh->real_escape_string($speciesid_verified));
						$check = $dbh->query($qry);
						
						//if affected rows, record successfully written
						if ($dbh->affected_rows == 0) 
						{ //no records written to rel_station_species table
							$maincontent.='<p>Error - Could not add to database:rel_station_species</p> 
								<p>Please go back and try again.</p>
								<FORM>
								<INPUT TYPE="button" VALUE="Back" onClick="history.go(-1);return true;"> 
								</FORM>';
						}
					} //mysql_num_rows check
											
					//redirect to my_regular_reports.php on success
					$maincontent.= "<script> window.location.replace('my_regular_reports.php') </script>";
							
				} //if $flag = 0
			} //if $_POST['btnsubmit']
		}//end else logged in
			
		$maincontent.=$spacer;
		echo $maincontent;
	?>
			
	<p>&nbsp;</p>
    </div><!-- MainContent -->


	<?php	
	WriteFooterNavigation();
	?>

</div> <!-- contentwrapper -->
</div> <!--wrapper -->

<?php
mysqli_close($dbh);
WriteGoogleAnalytics();
?>

</body>
</html>